"""
Meal database for the Healthy Meal Planner.
Contains a curated list of meals with nutritional info and metadata.
"""

MEALS = [
    # Breakfast
    {
        "name": "Oatmeal with Berries",
        "category": "Breakfast",
        "calories": 320,
        "protein": 10,
        "carbs": 58,
        "fat": 6,
        "fiber": 8,
        "tags": ["vegetarian", "vegan", "high-fiber"],
        "ingredients": ["rolled oats", "mixed berries", "almond milk", "honey", "chia seeds"],
        "prep_time": 10,
    },
    {
        "name": "Greek Yogurt Parfait",
        "category": "Breakfast",
        "calories": 280,
        "protein": 18,
        "carbs": 36,
        "fat": 5,
        "fiber": 4,
        "tags": ["vegetarian", "high-protein"],
        "ingredients": ["greek yogurt", "granola", "strawberries", "blueberries", "honey"],
        "prep_time": 5,
    },
    {
        "name": "Avocado Toast with Eggs",
        "category": "Breakfast",
        "calories": 420,
        "protein": 18,
        "carbs": 38,
        "fat": 22,
        "fiber": 8,
        "tags": ["vegetarian", "high-protein"],
        "ingredients": ["whole grain bread", "avocado", "eggs", "cherry tomatoes", "red pepper flakes"],
        "prep_time": 15,
    },
    {
        "name": "Smoothie Bowl",
        "category": "Breakfast",
        "calories": 350,
        "protein": 12,
        "carbs": 60,
        "fat": 8,
        "fiber": 9,
        "tags": ["vegetarian", "vegan", "high-fiber"],
        "ingredients": ["frozen banana", "frozen mango", "spinach", "almond milk", "granola", "kiwi"],
        "prep_time": 10,
    },

    # Lunch
    {
        "name": "Paneer Tikka Salad",
        "category": "Lunch",
        "calories": 360,
        "protein": 28,
        "carbs": 18,
        "fat": 18,
        "fiber": 5,
        "tags": ["vegetarian", "high-protein", "low-carb", "gluten-free"],
        "ingredients": ["paneer", "romaine lettuce", "cherry tomatoes", "cucumber", "olive oil", "lemon", "spices"],
        "prep_time": 20,
    },
    {
        "name": "Quinoa Buddha Bowl",
        "category": "Lunch",
        "calories": 450,
        "protein": 18,
        "carbs": 62,
        "fat": 14,
        "fiber": 10,
        "tags": ["vegetarian", "vegan", "high-fiber", "gluten-free"],
        "ingredients": ["quinoa", "chickpeas", "roasted sweet potato", "spinach", "tahini", "lemon"],
        "prep_time": 30,
    },
    {
        "name": "Chickpea & Veggie Wrap",
        "category": "Lunch",
        "calories": 400,
        "protein": 18,
        "carbs": 52,
        "fat": 12,
        "fiber": 10,
        "tags": ["vegetarian", "vegan", "high-fiber"],
        "ingredients": ["whole wheat tortilla", "chickpeas", "hummus", "spinach", "bell pepper", "red onion", "lemon"],
        "prep_time": 10,
    },
    {
        "name": "Lentil Soup",
        "category": "Lunch",
        "calories": 310,
        "protein": 18,
        "carbs": 50,
        "fat": 4,
        "fiber": 14,
        "tags": ["vegetarian", "vegan", "high-fiber", "gluten-free"],
        "ingredients": ["red lentils", "carrots", "celery", "onion", "cumin", "turmeric", "vegetable broth"],
        "prep_time": 35,
    },

    # Dinner
    {
        "name": "Paneer & Veggie Curry",
        "category": "Dinner",
        "calories": 460,
        "protein": 28,
        "carbs": 30,
        "fat": 22,
        "fiber": 6,
        "tags": ["vegetarian", "high-protein", "gluten-free"],
        "ingredients": ["paneer", "spinach", "tomatoes", "onion", "garlic", "ginger", "garam masala", "olive oil", "brown rice"],
        "prep_time": 30,
    },
    {
        "name": "Tofu Stir-Fry",
        "category": "Dinner",
        "calories": 380,
        "protein": 22,
        "carbs": 34,
        "fat": 14,
        "fiber": 7,
        "tags": ["vegetarian", "vegan", "high-protein", "low-calorie"],
        "ingredients": ["tofu", "broccoli", "bell peppers", "snap peas", "soy sauce", "ginger", "garlic", "brown rice"],
        "prep_time": 25,
    },
    {
        "name": "Black Bean Tacos",
        "category": "Dinner",
        "calories": 390,
        "protein": 16,
        "carbs": 58,
        "fat": 12,
        "fiber": 14,
        "tags": ["vegetarian", "vegan", "high-fiber"],
        "ingredients": ["corn tortillas", "black beans", "avocado", "salsa", "lime", "cilantro", "red cabbage"],
        "prep_time": 20,
    },
    {
        "name": "Spaghetti with Lentil Sauce",
        "category": "Dinner",
        "calories": 490,
        "protein": 24,
        "carbs": 68,
        "fat": 10,
        "fiber": 14,
        "tags": ["vegetarian", "vegan", "high-fiber"],
        "ingredients": ["whole wheat spaghetti", "red lentils", "tomato sauce", "onion", "garlic", "basil", "olive oil"],
        "prep_time": 35,
    },

    # Snacks
    {
        "name": "Apple with Almond Butter",
        "category": "Snack",
        "calories": 200,
        "protein": 5,
        "carbs": 28,
        "fat": 9,
        "fiber": 5,
        "tags": ["vegetarian", "vegan", "gluten-free"],
        "ingredients": ["apple", "almond butter"],
        "prep_time": 2,
    },
    {
        "name": "Hummus & Veggie Sticks",
        "category": "Snack",
        "calories": 180,
        "protein": 7,
        "carbs": 22,
        "fat": 8,
        "fiber": 6,
        "tags": ["vegetarian", "vegan", "gluten-free", "high-fiber"],
        "ingredients": ["hummus", "carrots", "celery", "cucumber", "bell pepper"],
        "prep_time": 5,
    },
    {
        "name": "Mixed Nuts & Dried Fruit",
        "category": "Snack",
        "calories": 220,
        "protein": 6,
        "carbs": 24,
        "fat": 12,
        "fiber": 3,
        "tags": ["vegetarian", "vegan", "gluten-free"],
        "ingredients": ["almonds", "walnuts", "cashews", "raisins", "dried cranberries"],
        "prep_time": 1,
    },
]

DIETARY_GOALS = {
    "Weight Loss": {"calories": 1500, "protein": 100, "carbs": 150, "fat": 55, "fiber": 25},
    "Muscle Gain": {"calories": 2500, "protein": 160, "carbs": 280, "fat": 80, "fiber": 30},
    "Maintenance": {"calories": 2000, "protein": 120, "carbs": 220, "fat": 65, "fiber": 28},
    "Heart Health": {"calories": 1800, "protein": 110, "carbs": 200, "fat": 60, "fiber": 35},
    "Custom": {"calories": 2000, "protein": 120, "carbs": 220, "fat": 65, "fiber": 28},
}

ALL_TAGS = sorted({tag for meal in MEALS for tag in meal["tags"]})
CATEGORIES = ["Breakfast", "Lunch", "Dinner", "Snack"]
